name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
    types: [ 'opened', 'synchronize' ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Copy .env file
        run: |
          cp .env.example .env
          echo "VITE_APP_NAME='Crystal Desarrollo'" >> .env
      - name: Install NPM dependencies
        run: npm ci
      - name: Build React
        run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: public/build

  deploy-production:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: [ 'build' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build
          path: public/build
      - name: Deploy laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd domains/crystaldesarrollo.com/public_html
            git pull
            rm -rf bootstrap/cache/*.php
            php ~/composer.phar install --no-dev --no-interaction --optimize-autoloader --no-plugins --no-progress --no-ansi --no-scripts
            php artisan migrate --force
            php artisan optimize
            php artisan event:cache
            php artisan queue:restart
      - name: Deploy React
        uses: nogsantos/scp-deploy@master
        with:
          src: ./public/*
          host: ${{ secrets.SSH_HOST }}
          remote: domains/crystaldesarrollo.com/public_html/public
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
